---
# --------------------------------------------------------------
# PersistentVolumeClaim (PVC)
# Provides persistent disk storage for Elasticsearch.
# Without this, logs and index data would be lost on pod restart.
# --------------------------------------------------------------
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: elasticsearch-pvc              # Name of the PVC
  namespace: logging                   # Lives in the logging namespace
spec:
  accessModes:
    - ReadWriteOnce                    # Only one node can mount this volume
  resources:
    requests:
      storage: 2Gi                     # Allocate 2Gi of persistent storage
  storageClassName: standard           # Default StorageClass used by Minikube

---
# --------------------------------------------------------------
# Elasticsearch Deployment (Elasticsearch 8.x)
# Runs Elasticsearch in single-node mode.
# NOTE: ES 8.x is REQUIRED for compatibility with cgroup v2
#       (ES 7.x crashes in Minikube with Java NPE).
# --------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: elasticsearch                  # Deployment name
  namespace: logging
spec:
  replicas: 1                           # Single-node ES (fine for logging stack)
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
        - name: elasticsearch
          # ------------------------------------------------------
          # IMPORTANT:
          # Using Elasticsearch 8.15.0 to avoid cgroup v2 crash.
          # ------------------------------------------------------
          image: docker.elastic.co/elasticsearch/elasticsearch:8.15.0

          # ------------------------------------------------------
          # Environment variables for Elasticsearch behavior
          # ------------------------------------------------------
          env:
            - name: discovery.type
              value: single-node          # ES won't try to form a cluster

            - name: ES_JAVA_OPTS
              value: "-Xms512m -Xmx512m"  # JVM heap: set to 50% of pod RAM

            # Security disabled for simplicity.
            # ES8 enables security by default unless turned off.
            - name: xpack.security.enabled
              value: "false"

          # ------------------------------------------------------
          # Expose Elasticsearch HTTP REST API
          # Used by:
          #  - Logstash output
          #  - Kibana
          #  - curl/dev tools
          # ------------------------------------------------------
          ports:
            - containerPort: 9200

          # ------------------------------------------------------
          # Resource requests & limits
          # Must be sufficient for ES to pass bootstrap checks.
          # ------------------------------------------------------
          resources:
            limits:
              memory: "2Gi"
              cpu: "1"
            requests:
              memory: "1Gi"
              cpu: "500m"

          # ------------------------------------------------------
          # Mount the persistent data directory
          # Ensures index data survives pod restarts.
          # ------------------------------------------------------
          volumeMounts:
            - mountPath: /usr/share/elasticsearch/data
              name: elasticsearch-storage

      # ------------------------------------------------------
      # Attach the PersistentVolumeClaim (PVC)
      # ------------------------------------------------------
      volumes:
        - name: elasticsearch-storage
          persistentVolumeClaim:
            claimName: elasticsearch-pvc

---
# --------------------------------------------------------------
# Elasticsearch Service
# Internal cluster service allowing Logstash & Kibana to reach ES.
# --------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: elasticsearch                 # DNS name inside logging namespace
  namespace: logging
spec:
  selector:
    app: elasticsearch                # Routes traffic to ES pod(s)
  ports:
    - protocol: TCP
      port: 9200                      # Service port
      targetPort: 9200                # Container port exposed above
