---
# --------------------------------------------------------------
# Kibana Deployment
# Kibana provides the *frontend* of the ELK stack.
# It allows you to:
#   • search logs coming from Filebeat → Logstash → Elasticsearch
#   • build dashboards, charts, alerts
#   • visually explore system/application behaviour
#
# This deployment runs one Kibana pod inside the "logging" namespace.
# --------------------------------------------------------------
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kibana                     # Name of the deployment
  namespace: logging               # Deploy Kibana to the logging namespace
spec:
  replicas: 1                      # One Kibana instance is enough for dev setups
  selector:
    matchLabels:
      app: kibana                  # Match pods labelled "app=kibana"
  template:
    metadata:
      labels:
        app: kibana
    spec:
      containers:
        - name: kibana
          image: docker.elastic.co/kibana/kibana:7.17.0  # Official Kibana image

          # -----------------------------------------------
          # Kibana must know where Elasticsearch lives.
          # It communicates with ES to:
          #   • fetch log indices
          #   • power visualisations
          #   • store saved dashboards
          #
          # The DNS name "elasticsearch" works because of the
          # corresponding Service object in the same namespace.
          # -----------------------------------------------
          env:
            - name: ELASTICSEARCH_HOSTS
              value: http://elasticsearch:9200

          # -----------------------------------------------
          # Kibana UI runs on port 5601 inside the container
          # -----------------------------------------------
          ports:
            - containerPort: 5601

---
# --------------------------------------------------------------
# Kibana Service
# This exposes Kibana *externally* via NodePort.
#
# After applying this manifest, you can reach Kibana using:
#
#   http://<NODE_IP>:30601
#
# For example:
#   • Minikube:   http://$(minikube ip):30601
#   • VM cluster: http://VM_PUBLIC_IP:30601
#
# Once opened, you can explore logs visually.
# --------------------------------------------------------------
apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: logging
spec:
  type: NodePort                  # Makes Kibana available outside the cluster
  selector:
    app: kibana                   # Routes traffic to pods with this label
  ports:
    - port: 5601                  # Service port (internal to cluster)
      nodePort: 30601             # Public-access port on each Kubernetes node
